swagger: '2.0'
info:
  title: ViáFluvial User Service API
  version: 1.0.0
host: localhost:8080
basePath: /api/v1
schemes:
  - http

paths:
  /users:
    post:
      tags:
        - Usuários
      summary: Criar novo usuário
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: body
          schema:
            $ref: '#/definitions/UserDTO'
      responses:
        201:
          description: Usuário criado com sucesso
        400:
          description: Dados inválidos
        409:
          description: Email já registrado

    get:
      tags:
        - Usuários
      summary: Listar todos os usuários
      produces:
        - application/json
      responses:
        200:
          description: Lista de usuários

  /users/{id}:
    get:
      tags:
        - Usuários
      summary: Obter usuário por ID
      produces:
        - application/json
      parameters:
        - name: id
          in: path
          required: true
          type: string
          format: uuid
      responses:
        200:
          description: Usuário encontrado
        404:
          description: Usuário não encontrado

    put:
      tags:
        - Usuários
      summary: Atualizar usuário
      consumes:
        - application/json
      parameters:
        - name: id
          in: path
          required: true
          type: string
          format: uuid
        - in: body
          name: body
          schema:
            $ref: '#/definitions/UserDTO'
      responses:
        200:
          description: Usuário atualizado

    delete:
      tags:
        - Usuários
      summary: Deletar usuário
      parameters:
        - name: id
          in: path
          required: true
          type: string
          format: uuid
      responses:
        204:
          description: Usuário deletado

  /users/email/{email}:
    get:
      tags:
        - Usuários
      summary: Obter usuário por email
      produces:
        - application/json
      parameters:
        - name: email
          in: path
          required: true
          type: string
      responses:
        200:
          description: Usuário encontrado

  /users/type/{userType}:
    get:
      tags:
        - Usuários
      summary: Listar usuários por tipo
      produces:
        - application/json
      parameters:
        - name: userType
          in: path
          required: true
          type: string
          enum: [PASSENGER, BOATMAN, AGENCY, ADMIN]
      responses:
        200:
          description: Lista de usuários

  /passengers:
    post:
      tags:
        - Passageiros
      summary: Criar novo passageiro
      consumes:
        - application/json
      parameters:
        - in: body
          name: body
          schema:
            $ref: '#/definitions/PassengerDTO'
      responses:
        201:
          description: Passageiro criado

    get:
      tags:
        - Passageiros
      summary: Listar passageiros (filtro por CPF)
      produces:
        - application/json
      parameters:
        - name: cpf
          in: query
          required: false
          type: string
          description: CPF para filtrar passageiros
      responses:
        200:
          description: Lista paginada de passageiros

  /passengers/exists:
    get:
      tags:
        - Passageiros
      summary: Validar existência de passageiro
      produces:
        - application/json
      parameters:
        - name: cpf
          in: query
          required: true
          type: string
          description: CPF para validação
      responses:
        200:
          description: Resultado da validação de existência

  /boatmen:
    get:
      tags:
        - Barqueiros
      summary: Listar barqueiros (filtro por CPF/CNPJ)
      produces:
        - application/json
      parameters:
        - name: cpf
          in: query
          required: false
          type: string
          description: CPF para filtrar barqueiros
        - name: cnpj
          in: query
          required: false
          type: string
          description: CNPJ para filtrar barqueiros
      responses:
        200:
          description: Lista paginada de barqueiros

  /boatmen/exists:
    get:
      tags:
        - Barqueiros
      summary: Validar existência de barqueiro
      produces:
        - application/json
      parameters:
        - name: cpf
          in: query
          required: false
          type: string
          description: CPF para validação
        - name: cnpj
          in: query
          required: false
          type: string
          description: CNPJ para validação
      responses:
        200:
          description: Resultado da validação de existência

  /agencies/exists:
    get:
      tags:
        - Agências
      summary: Validar existência de agência
      produces:
        - application/json
      parameters:
        - name: cnpj
          in: query
          required: true
          type: string
          description: CNPJ para validação
      responses:
        200:
          description: Resultado da validação de existência

  /passengers/{id}:
    get:
      tags:
        - Passageiros
      summary: Obter passageiro por ID
      parameters:
        - name: id
          in: path
          required: true
          type: string
          format: uuid
      responses:
        200:
          description: Passageiro encontrado

    put:
      tags:
        - Passageiros
      summary: Atualizar passageiro
      parameters:
        - name: id
          in: path
          required: true
          type: string
          format: uuid
        - in: body
          name: body
          schema:
            $ref: '#/definitions/PassengerDTO'
      responses:
        200:
          description: Passageiro atualizado

  /passengers/user/{userId}:
    get:
      tags:
        - Passageiros
      summary: Obter passageiro por ID do usuário
      parameters:
        - name: userId
          in: path
          required: true
          type: string
          format: uuid
      responses:
        200:
          description: Passageiro encontrado

  /auth/register:
    post:
      tags:
        - Autenticação
      summary: Registrar novo usuário
      consumes:
        - application/json
      parameters:
        - in: body
          name: body
          schema:
            $ref: '#/definitions/UserDTO'
      responses:
        201:
          description: Usuário registrado

  /auth/login:
    post:
      tags:
        - Autenticação
      summary: Login de usuário
      consumes:
        - application/json
      parameters:
        - in: body
          name: body
          schema:
            $ref: '#/definitions/AuthDTO'
      responses:
        200:
          description: Login bem-sucedido
        401:
          description: Credenciais inválidas

definitions:
  UserDTO:
    type: object
    required:
      - email
      - password
      - fullName
      - phone
      - userType
    properties:
      id:
        type: string
        format: uuid
      email:
        type: string
        format: email
        example: usuario@example.com
      password:
        type: string
        minLength: 8
        example: SenhaForte123!
      fullName:
        type: string
        example: João Silva
      phone:
        type: string
        example: "(92) 98765-4321"
      userType:
        type: string
        enum: [PASSENGER, BOATMAN, AGENCY, ADMIN]
      status:
        type: string
        enum: [PENDING, APPROVED, ACTIVE, BLOCKED]
      emailVerified:
        type: boolean
      createdAt:
        type: string
        format: date-time
      updatedAt:
        type: string
        format: date-time
      lastLogin:
        type: string
        format: date-time

  PassengerDTO:
    type: object
    required:
      - userId
      - cpf
    properties:
      id:
        type: string
        format: uuid
      userId:
        type: string
        format: uuid
      cpf:
        type: string
        pattern: "^\\d{3}\\.\\d{3}\\.\\d{3}-\\d{2}$"
        example: "123.456.789-00"
      rg:
        type: string
        example: "12.345.678-9"
      birthDate:
        type: string
        format: date
        example: "1990-05-15"
      address:
        type: string
        example: "Rua das Flores, 123"
      city:
        type: string
        example: Manaus
      state:
        type: string
        maxLength: 2
        example: AM
      zipCode:
        type: string
        example: "69000-000"
      preferredCabinType:
        type: string
        enum: [STANDARD, EXECUTIVE, VIP, SUITE]
      totalTrips:
        type: integer
      totalSpent:
        type: number
        format: decimal
      createdAt:
        type: string
        format: date-time
      updatedAt:
        type: string
        format: date-time

  AuthDTO:
    type: object
    required:
      - email
      - password
    properties:
      email:
        type: string
        format: email
      password:
        type: string

  AuthResponseDTO:
    type: object
    properties:
      accessToken:
        type: string
      refreshToken:
        type: string
      tokenType:
        type: string
        example: Bearer
      expiresIn:
        type: integer
        example: 3600
      user:
        $ref: '#/definitions/UserDTO'
