/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.6.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.viafluvial.srvusuario.adapters.in.web.api;

import com.viafluvial.srvusuario.adapters.in.web.dto.ApprovalCreateDTOApi;
import com.viafluvial.srvusuario.adapters.in.web.dto.ApprovalDTOApi;
import com.viafluvial.srvusuario.adapters.in.web.dto.ApprovalStatusApi;
import com.viafluvial.srvusuario.adapters.in.web.dto.PagedApprovalResponseApi;
import java.util.UUID;
import io.swagger.v3.oas.annotations.ExternalDocumentation;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.Parameters;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.context.request.NativeWebRequest;
import org.springframework.web.multipart.MultipartFile;

import jakarta.validation.Valid;
import jakarta.validation.constraints.*;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import jakarta.annotation.Generated;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2026-02-08T03:10:33.091278071Z[Etc/UTC]", comments = "Generator version: 7.6.0")
@Validated
@Tag(name = "Approvals", description = "the Approvals API")
public interface ApprovalsApi {

    default Optional<NativeWebRequest> getRequest() {
        return Optional.empty();
    }

    /**
     * PATCH /approvals/{id}/activate : Activate approval entity
     *
     * @param id  (required)
     * @return Approval updated (status code 200)
     */
    @Operation(
        operationId = "activateApproval",
        summary = "Activate approval entity",
        tags = { "Approvals" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Approval updated", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ApprovalDTOApi.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.PATCH,
        value = "/approvals/{id}/activate",
        produces = { "application/json" }
    )
    
    default ResponseEntity<ApprovalDTOApi> activateApproval(
        @Parameter(name = "id", description = "", required = true, in = ParameterIn.PATH) @PathVariable("id") UUID id
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"createdAt\" : \"2000-01-23T04:56:07.000+00:00\", \"documents\" : \"documents\", \"entityType\" : \"USER\", \"entityId\" : \"046b6c7f-0b8a-43b9-b35d-6489e6daee91\", \"id\" : \"046b6c7f-0b8a-43b9-b35d-6489e6daee91\", \"type\" : \"type\", \"status\" : \"PENDING\", \"updatedAt\" : \"2000-01-23T04:56:07.000+00:00\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    /**
     * PATCH /approvals/{id}/approve : Approve approval entity
     *
     * @param id  (required)
     * @return Approval updated (status code 200)
     */
    @Operation(
        operationId = "approveApproval",
        summary = "Approve approval entity",
        tags = { "Approvals" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Approval updated", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ApprovalDTOApi.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.PATCH,
        value = "/approvals/{id}/approve",
        produces = { "application/json" }
    )
    
    default ResponseEntity<ApprovalDTOApi> approveApproval(
        @Parameter(name = "id", description = "", required = true, in = ParameterIn.PATH) @PathVariable("id") UUID id
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"createdAt\" : \"2000-01-23T04:56:07.000+00:00\", \"documents\" : \"documents\", \"entityType\" : \"USER\", \"entityId\" : \"046b6c7f-0b8a-43b9-b35d-6489e6daee91\", \"id\" : \"046b6c7f-0b8a-43b9-b35d-6489e6daee91\", \"type\" : \"type\", \"status\" : \"PENDING\", \"updatedAt\" : \"2000-01-23T04:56:07.000+00:00\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    /**
     * PATCH /approvals/{id}/block : Block approval entity
     *
     * @param id  (required)
     * @return Approval updated (status code 200)
     */
    @Operation(
        operationId = "blockApproval",
        summary = "Block approval entity",
        tags = { "Approvals" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Approval updated", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ApprovalDTOApi.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.PATCH,
        value = "/approvals/{id}/block",
        produces = { "application/json" }
    )
    
    default ResponseEntity<ApprovalDTOApi> blockApproval(
        @Parameter(name = "id", description = "", required = true, in = ParameterIn.PATH) @PathVariable("id") UUID id
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"createdAt\" : \"2000-01-23T04:56:07.000+00:00\", \"documents\" : \"documents\", \"entityType\" : \"USER\", \"entityId\" : \"046b6c7f-0b8a-43b9-b35d-6489e6daee91\", \"id\" : \"046b6c7f-0b8a-43b9-b35d-6489e6daee91\", \"type\" : \"type\", \"status\" : \"PENDING\", \"updatedAt\" : \"2000-01-23T04:56:07.000+00:00\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    /**
     * POST /approvals : Create approval
     *
     * @param approvalCreateDTOApi  (required)
     * @return Approval created (status code 201)
     *         or Invalid request (status code 400)
     */
    @Operation(
        operationId = "createApproval",
        summary = "Create approval",
        tags = { "Approvals" },
        responses = {
            @ApiResponse(responseCode = "201", description = "Approval created", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ApprovalDTOApi.class))
            }),
            @ApiResponse(responseCode = "400", description = "Invalid request")
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = "/approvals",
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    
    default ResponseEntity<ApprovalDTOApi> createApproval(
        @Parameter(name = "ApprovalCreateDTOApi", description = "", required = true) @Valid @RequestBody ApprovalCreateDTOApi approvalCreateDTOApi
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"createdAt\" : \"2000-01-23T04:56:07.000+00:00\", \"documents\" : \"documents\", \"entityType\" : \"USER\", \"entityId\" : \"046b6c7f-0b8a-43b9-b35d-6489e6daee91\", \"id\" : \"046b6c7f-0b8a-43b9-b35d-6489e6daee91\", \"type\" : \"type\", \"status\" : \"PENDING\", \"updatedAt\" : \"2000-01-23T04:56:07.000+00:00\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    /**
     * GET /approvals : List approvals
     *
     * @param status  (optional)
     * @param page  (optional, default to 1)
     * @param size  (optional, default to 20)
     * @return Paged approvals (status code 200)
     */
    @Operation(
        operationId = "listApprovals",
        summary = "List approvals",
        tags = { "Approvals" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Paged approvals", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = PagedApprovalResponseApi.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/approvals",
        produces = { "application/json" }
    )
    
    default ResponseEntity<PagedApprovalResponseApi> listApprovals(
        @Parameter(name = "status", description = "", in = ParameterIn.QUERY) @Valid @RequestParam(value = "status", required = false) ApprovalStatusApi status,
        @Min(1) @Parameter(name = "page", description = "", in = ParameterIn.QUERY) @Valid @RequestParam(value = "page", required = false, defaultValue = "1") Integer page,
        @Min(1) @Max(200) @Parameter(name = "size", description = "", in = ParameterIn.QUERY) @Valid @RequestParam(value = "size", required = false, defaultValue = "20") Integer size
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"totalItems\" : 1, \"size\" : 6, \"totalPages\" : 5, \"page\" : 0, \"items\" : [ { \"createdAt\" : \"2000-01-23T04:56:07.000+00:00\", \"documents\" : \"documents\", \"entityType\" : \"USER\", \"entityId\" : \"046b6c7f-0b8a-43b9-b35d-6489e6daee91\", \"id\" : \"046b6c7f-0b8a-43b9-b35d-6489e6daee91\", \"type\" : \"type\", \"status\" : \"PENDING\", \"updatedAt\" : \"2000-01-23T04:56:07.000+00:00\" }, { \"createdAt\" : \"2000-01-23T04:56:07.000+00:00\", \"documents\" : \"documents\", \"entityType\" : \"USER\", \"entityId\" : \"046b6c7f-0b8a-43b9-b35d-6489e6daee91\", \"id\" : \"046b6c7f-0b8a-43b9-b35d-6489e6daee91\", \"type\" : \"type\", \"status\" : \"PENDING\", \"updatedAt\" : \"2000-01-23T04:56:07.000+00:00\" } ] }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    /**
     * PATCH /approvals/{id}/request-more-info : Request more info
     *
     * @param id  (required)
     * @return Approval updated (status code 200)
     */
    @Operation(
        operationId = "requestMoreInfo",
        summary = "Request more info",
        tags = { "Approvals" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Approval updated", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ApprovalDTOApi.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.PATCH,
        value = "/approvals/{id}/request-more-info",
        produces = { "application/json" }
    )
    
    default ResponseEntity<ApprovalDTOApi> requestMoreInfo(
        @Parameter(name = "id", description = "", required = true, in = ParameterIn.PATH) @PathVariable("id") UUID id
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"createdAt\" : \"2000-01-23T04:56:07.000+00:00\", \"documents\" : \"documents\", \"entityType\" : \"USER\", \"entityId\" : \"046b6c7f-0b8a-43b9-b35d-6489e6daee91\", \"id\" : \"046b6c7f-0b8a-43b9-b35d-6489e6daee91\", \"type\" : \"type\", \"status\" : \"PENDING\", \"updatedAt\" : \"2000-01-23T04:56:07.000+00:00\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    /**
     * PATCH /approvals/{id}/unblock : Unblock approval entity
     *
     * @param id  (required)
     * @return Approval updated (status code 200)
     */
    @Operation(
        operationId = "unblockApproval",
        summary = "Unblock approval entity",
        tags = { "Approvals" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Approval updated", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ApprovalDTOApi.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.PATCH,
        value = "/approvals/{id}/unblock",
        produces = { "application/json" }
    )
    
    default ResponseEntity<ApprovalDTOApi> unblockApproval(
        @Parameter(name = "id", description = "", required = true, in = ParameterIn.PATH) @PathVariable("id") UUID id
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"createdAt\" : \"2000-01-23T04:56:07.000+00:00\", \"documents\" : \"documents\", \"entityType\" : \"USER\", \"entityId\" : \"046b6c7f-0b8a-43b9-b35d-6489e6daee91\", \"id\" : \"046b6c7f-0b8a-43b9-b35d-6489e6daee91\", \"type\" : \"type\", \"status\" : \"PENDING\", \"updatedAt\" : \"2000-01-23T04:56:07.000+00:00\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }

}
