/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.6.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.viafluvial.srvusuario.adapters.in.web.api;

import com.viafluvial.srvusuario.adapters.in.web.dto.BoatmanDTOApi;
import com.viafluvial.srvusuario.adapters.in.web.dto.BoatmanDocumentsDTOApi;
import org.springframework.format.annotation.DateTimeFormat;
import com.viafluvial.srvusuario.adapters.in.web.dto.ExistsResponseApi;
import java.time.LocalDateTime;
import com.viafluvial.srvusuario.adapters.in.web.dto.PagedBoatmanResponseApi;
import java.util.UUID;
import io.swagger.v3.oas.annotations.ExternalDocumentation;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.Parameters;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.context.request.NativeWebRequest;
import org.springframework.web.multipart.MultipartFile;

import jakarta.validation.Valid;
import jakarta.validation.constraints.*;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import jakarta.annotation.Generated;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2026-02-07T21:43:37.860179204Z[Etc/UTC]", comments = "Generator version: 7.6.0")
@Validated
@Tag(name = "Boatmen", description = "the Boatmen API")
public interface BoatmenApi {

    default Optional<NativeWebRequest> getRequest() {
        return Optional.empty();
    }

    /**
     * GET /boatmen/exists : Check boatman existence by cpf or cnpj
     *
     * @param cpf  (optional)
     * @param cnpj  (optional)
     * @return Exists response (status code 200)
     */
    @Operation(
        operationId = "boatmanExists",
        summary = "Check boatman existence by cpf or cnpj",
        tags = { "Boatmen" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Exists response", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ExistsResponseApi.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/boatmen/exists",
        produces = { "application/json" }
    )
    
    default ResponseEntity<ExistsResponseApi> boatmanExists(
        @Parameter(name = "cpf", description = "", in = ParameterIn.QUERY) @Valid @RequestParam(value = "cpf", required = false) String cpf,
        @Parameter(name = "cnpj", description = "", in = ParameterIn.QUERY) @Valid @RequestParam(value = "cnpj", required = false) String cnpj
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"exists\" : true }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    /**
     * POST /boatmen : Create boatman
     *
     * @param boatmanDTOApi  (required)
     * @return Boatman created (status code 201)
     *         or Invalid request (status code 400)
     *         or CPF or CNPJ already exists (status code 409)
     */
    @Operation(
        operationId = "createBoatman",
        summary = "Create boatman",
        tags = { "Boatmen" },
        responses = {
            @ApiResponse(responseCode = "201", description = "Boatman created", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = BoatmanDTOApi.class))
            }),
            @ApiResponse(responseCode = "400", description = "Invalid request"),
            @ApiResponse(responseCode = "409", description = "CPF or CNPJ already exists")
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = "/boatmen",
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    
    default ResponseEntity<BoatmanDTOApi> createBoatman(
        @Parameter(name = "BoatmanDTOApi", description = "", required = true) @Valid @RequestBody BoatmanDTOApi boatmanDTOApi
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"createdAt\" : \"2000-01-23T04:56:07.000+00:00\", \"totalTrips\" : 6, \"companyName\" : \"companyName\", \"cpf\" : \"cpf\", \"rating\" : 0.8008281904610115, \"id\" : \"046b6c7f-0b8a-43b9-b35d-6489e6daee91\", \"cnpj\" : \"cnpj\", \"totalRevenue\" : 1.4658129805029452, \"approvedAt\" : \"2000-01-23T04:56:07.000+00:00\", \"userId\" : \"046b6c7f-0b8a-43b9-b35d-6489e6daee91\", \"updatedAt\" : \"2000-01-23T04:56:07.000+00:00\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    /**
     * GET /boatmen/{id} : Get boatman by id
     *
     * @param id  (required)
     * @return Boatman found (status code 200)
     *         or Boatman not found (status code 404)
     */
    @Operation(
        operationId = "getBoatmanById",
        summary = "Get boatman by id",
        tags = { "Boatmen" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Boatman found", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = BoatmanDTOApi.class))
            }),
            @ApiResponse(responseCode = "404", description = "Boatman not found")
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/boatmen/{id}",
        produces = { "application/json" }
    )
    
    default ResponseEntity<BoatmanDTOApi> getBoatmanById(
        @Parameter(name = "id", description = "", required = true, in = ParameterIn.PATH) @PathVariable("id") UUID id
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"createdAt\" : \"2000-01-23T04:56:07.000+00:00\", \"totalTrips\" : 6, \"companyName\" : \"companyName\", \"cpf\" : \"cpf\", \"rating\" : 0.8008281904610115, \"id\" : \"046b6c7f-0b8a-43b9-b35d-6489e6daee91\", \"cnpj\" : \"cnpj\", \"totalRevenue\" : 1.4658129805029452, \"approvedAt\" : \"2000-01-23T04:56:07.000+00:00\", \"userId\" : \"046b6c7f-0b8a-43b9-b35d-6489e6daee91\", \"updatedAt\" : \"2000-01-23T04:56:07.000+00:00\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    /**
     * GET /boatmen/user/{userId} : Get boatman by user id
     *
     * @param userId  (required)
     * @return Boatman found (status code 200)
     *         or Boatman not found (status code 404)
     */
    @Operation(
        operationId = "getBoatmanByUserId",
        summary = "Get boatman by user id",
        tags = { "Boatmen" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Boatman found", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = BoatmanDTOApi.class))
            }),
            @ApiResponse(responseCode = "404", description = "Boatman not found")
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/boatmen/user/{userId}",
        produces = { "application/json" }
    )
    
    default ResponseEntity<BoatmanDTOApi> getBoatmanByUserId(
        @Parameter(name = "userId", description = "", required = true, in = ParameterIn.PATH) @PathVariable("userId") UUID userId
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"createdAt\" : \"2000-01-23T04:56:07.000+00:00\", \"totalTrips\" : 6, \"companyName\" : \"companyName\", \"cpf\" : \"cpf\", \"rating\" : 0.8008281904610115, \"id\" : \"046b6c7f-0b8a-43b9-b35d-6489e6daee91\", \"cnpj\" : \"cnpj\", \"totalRevenue\" : 1.4658129805029452, \"approvedAt\" : \"2000-01-23T04:56:07.000+00:00\", \"userId\" : \"046b6c7f-0b8a-43b9-b35d-6489e6daee91\", \"updatedAt\" : \"2000-01-23T04:56:07.000+00:00\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    /**
     * GET /boatmen/{id}/documents : Get boatman documents
     *
     * @param id  (required)
     * @return Documents (status code 200)
     *         or Boatman not found (status code 404)
     */
    @Operation(
        operationId = "getBoatmanDocuments",
        summary = "Get boatman documents",
        tags = { "Boatmen" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Documents", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = BoatmanDocumentsDTOApi.class))
            }),
            @ApiResponse(responseCode = "404", description = "Boatman not found")
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/boatmen/{id}/documents",
        produces = { "application/json" }
    )
    
    default ResponseEntity<BoatmanDocumentsDTOApi> getBoatmanDocuments(
        @Parameter(name = "id", description = "", required = true, in = ParameterIn.PATH) @PathVariable("id") UUID id
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"documentCpfUrl\" : \"documentCpfUrl\", \"documentCnpjUrl\" : \"documentCnpjUrl\", \"documentAddressProofUrl\" : \"documentAddressProofUrl\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    /**
     * GET /boatmen : Search boatmen
     *
     * @param cpf  (optional)
     * @param cnpj  (optional)
     * @param ratingMin  (optional)
     * @param approvedFrom  (optional)
     * @param approvedTo  (optional)
     * @param createdFrom  (optional)
     * @param createdTo  (optional)
     * @param page  (optional, default to 1)
     * @param size  (optional, default to 20)
     * @return Paged boatmen (status code 200)
     */
    @Operation(
        operationId = "searchBoatmen",
        summary = "Search boatmen",
        tags = { "Boatmen" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Paged boatmen", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = PagedBoatmanResponseApi.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/boatmen",
        produces = { "application/json" }
    )
    
    default ResponseEntity<PagedBoatmanResponseApi> searchBoatmen(
        @Parameter(name = "cpf", description = "", in = ParameterIn.QUERY) @Valid @RequestParam(value = "cpf", required = false) String cpf,
        @Parameter(name = "cnpj", description = "", in = ParameterIn.QUERY) @Valid @RequestParam(value = "cnpj", required = false) String cnpj,
        @Parameter(name = "ratingMin", description = "", in = ParameterIn.QUERY) @Valid @RequestParam(value = "ratingMin", required = false) Double ratingMin,
        @Parameter(name = "approvedFrom", description = "", in = ParameterIn.QUERY) @Valid @RequestParam(value = "approvedFrom", required = false) @DateTimeFormat(iso = DateTimeFormat.ISO.DATE_TIME) LocalDateTime approvedFrom,
        @Parameter(name = "approvedTo", description = "", in = ParameterIn.QUERY) @Valid @RequestParam(value = "approvedTo", required = false) @DateTimeFormat(iso = DateTimeFormat.ISO.DATE_TIME) LocalDateTime approvedTo,
        @Parameter(name = "createdFrom", description = "", in = ParameterIn.QUERY) @Valid @RequestParam(value = "createdFrom", required = false) @DateTimeFormat(iso = DateTimeFormat.ISO.DATE_TIME) LocalDateTime createdFrom,
        @Parameter(name = "createdTo", description = "", in = ParameterIn.QUERY) @Valid @RequestParam(value = "createdTo", required = false) @DateTimeFormat(iso = DateTimeFormat.ISO.DATE_TIME) LocalDateTime createdTo,
        @Min(1) @Parameter(name = "page", description = "", in = ParameterIn.QUERY) @Valid @RequestParam(value = "page", required = false, defaultValue = "1") Integer page,
        @Min(1) @Max(200) @Parameter(name = "size", description = "", in = ParameterIn.QUERY) @Valid @RequestParam(value = "size", required = false, defaultValue = "20") Integer size
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"totalItems\" : 2, \"size\" : 5, \"totalPages\" : 7, \"page\" : 5, \"items\" : [ { \"createdAt\" : \"2000-01-23T04:56:07.000+00:00\", \"totalTrips\" : 6, \"companyName\" : \"companyName\", \"cpf\" : \"cpf\", \"rating\" : 0.8008281904610115, \"id\" : \"046b6c7f-0b8a-43b9-b35d-6489e6daee91\", \"cnpj\" : \"cnpj\", \"totalRevenue\" : 1.4658129805029452, \"approvedAt\" : \"2000-01-23T04:56:07.000+00:00\", \"userId\" : \"046b6c7f-0b8a-43b9-b35d-6489e6daee91\", \"updatedAt\" : \"2000-01-23T04:56:07.000+00:00\" }, { \"createdAt\" : \"2000-01-23T04:56:07.000+00:00\", \"totalTrips\" : 6, \"companyName\" : \"companyName\", \"cpf\" : \"cpf\", \"rating\" : 0.8008281904610115, \"id\" : \"046b6c7f-0b8a-43b9-b35d-6489e6daee91\", \"cnpj\" : \"cnpj\", \"totalRevenue\" : 1.4658129805029452, \"approvedAt\" : \"2000-01-23T04:56:07.000+00:00\", \"userId\" : \"046b6c7f-0b8a-43b9-b35d-6489e6daee91\", \"updatedAt\" : \"2000-01-23T04:56:07.000+00:00\" } ] }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    /**
     * PATCH /boatmen/{id}/documents : Update boatman documents
     *
     * @param id  (required)
     * @param boatmanDocumentsDTOApi  (required)
     * @return Documents updated (status code 200)
     *         or Boatman not found (status code 404)
     */
    @Operation(
        operationId = "updateBoatmanDocuments",
        summary = "Update boatman documents",
        tags = { "Boatmen" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Documents updated", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = BoatmanDocumentsDTOApi.class))
            }),
            @ApiResponse(responseCode = "404", description = "Boatman not found")
        }
    )
    @RequestMapping(
        method = RequestMethod.PATCH,
        value = "/boatmen/{id}/documents",
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    
    default ResponseEntity<BoatmanDocumentsDTOApi> updateBoatmanDocuments(
        @Parameter(name = "id", description = "", required = true, in = ParameterIn.PATH) @PathVariable("id") UUID id,
        @Parameter(name = "BoatmanDocumentsDTOApi", description = "", required = true) @Valid @RequestBody BoatmanDocumentsDTOApi boatmanDocumentsDTOApi
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"documentCpfUrl\" : \"documentCpfUrl\", \"documentCnpjUrl\" : \"documentCnpjUrl\", \"documentAddressProofUrl\" : \"documentAddressProofUrl\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }

}
