/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.6.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.viafluvial.srvusuario.adapters.in.web.api;

import org.springframework.format.annotation.DateTimeFormat;
import com.viafluvial.srvusuario.adapters.in.web.dto.ExistsResponseApi;
import java.time.LocalDateTime;
import com.viafluvial.srvusuario.adapters.in.web.dto.PagedPassengerResponseApi;
import com.viafluvial.srvusuario.adapters.in.web.dto.PassengerDTOApi;
import java.util.UUID;
import io.swagger.v3.oas.annotations.ExternalDocumentation;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.Parameters;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.context.request.NativeWebRequest;
import org.springframework.web.multipart.MultipartFile;

import jakarta.validation.Valid;
import jakarta.validation.constraints.*;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import jakarta.annotation.Generated;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2026-02-08T03:10:33.091278071Z[Etc/UTC]", comments = "Generator version: 7.6.0")
@Validated
@Tag(name = "Passengers", description = "the Passengers API")
public interface PassengersApi {

    default Optional<NativeWebRequest> getRequest() {
        return Optional.empty();
    }

    /**
     * POST /passengers : Create passenger
     *
     * @param passengerDTOApi  (required)
     * @return Passenger created (status code 201)
     *         or Invalid request (status code 400)
     *         or CPF already exists (status code 409)
     */
    @Operation(
        operationId = "createPassenger",
        summary = "Create passenger",
        tags = { "Passengers" },
        responses = {
            @ApiResponse(responseCode = "201", description = "Passenger created", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = PassengerDTOApi.class))
            }),
            @ApiResponse(responseCode = "400", description = "Invalid request"),
            @ApiResponse(responseCode = "409", description = "CPF already exists")
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = "/passengers",
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    
    default ResponseEntity<PassengerDTOApi> createPassenger(
        @Parameter(name = "PassengerDTOApi", description = "", required = true) @Valid @RequestBody PassengerDTOApi passengerDTOApi
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"zipCode\" : \"zipCode\", \"address\" : \"address\", \"totalSpent\" : 6.027456183070403, \"city\" : \"city\", \"userId\" : \"046b6c7f-0b8a-43b9-b35d-6489e6daee91\", \"birthDate\" : \"2000-01-23\", \"createdAt\" : \"2000-01-23T04:56:07.000+00:00\", \"totalTrips\" : 0, \"preferredCabinType\" : \"STANDARD\", \"rg\" : \"rg\", \"cpf\" : \"cpf\", \"id\" : \"046b6c7f-0b8a-43b9-b35d-6489e6daee91\", \"state\" : \"state\", \"updatedAt\" : \"2000-01-23T04:56:07.000+00:00\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    /**
     * GET /passengers/{id} : Get passenger by id
     *
     * @param id  (required)
     * @return Passenger found (status code 200)
     *         or Passenger not found (status code 404)
     */
    @Operation(
        operationId = "getPassengerById",
        summary = "Get passenger by id",
        tags = { "Passengers" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Passenger found", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = PassengerDTOApi.class))
            }),
            @ApiResponse(responseCode = "404", description = "Passenger not found")
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/passengers/{id}",
        produces = { "application/json" }
    )
    
    default ResponseEntity<PassengerDTOApi> getPassengerById(
        @Parameter(name = "id", description = "", required = true, in = ParameterIn.PATH) @PathVariable("id") UUID id
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"zipCode\" : \"zipCode\", \"address\" : \"address\", \"totalSpent\" : 6.027456183070403, \"city\" : \"city\", \"userId\" : \"046b6c7f-0b8a-43b9-b35d-6489e6daee91\", \"birthDate\" : \"2000-01-23\", \"createdAt\" : \"2000-01-23T04:56:07.000+00:00\", \"totalTrips\" : 0, \"preferredCabinType\" : \"STANDARD\", \"rg\" : \"rg\", \"cpf\" : \"cpf\", \"id\" : \"046b6c7f-0b8a-43b9-b35d-6489e6daee91\", \"state\" : \"state\", \"updatedAt\" : \"2000-01-23T04:56:07.000+00:00\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    /**
     * GET /passengers/user/{userId} : Get passenger by user id
     *
     * @param userId  (required)
     * @return Passenger found (status code 200)
     *         or Passenger not found (status code 404)
     */
    @Operation(
        operationId = "getPassengerByUserId",
        summary = "Get passenger by user id",
        tags = { "Passengers" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Passenger found", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = PassengerDTOApi.class))
            }),
            @ApiResponse(responseCode = "404", description = "Passenger not found")
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/passengers/user/{userId}",
        produces = { "application/json" }
    )
    
    default ResponseEntity<PassengerDTOApi> getPassengerByUserId(
        @Parameter(name = "userId", description = "", required = true, in = ParameterIn.PATH) @PathVariable("userId") UUID userId
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"zipCode\" : \"zipCode\", \"address\" : \"address\", \"totalSpent\" : 6.027456183070403, \"city\" : \"city\", \"userId\" : \"046b6c7f-0b8a-43b9-b35d-6489e6daee91\", \"birthDate\" : \"2000-01-23\", \"createdAt\" : \"2000-01-23T04:56:07.000+00:00\", \"totalTrips\" : 0, \"preferredCabinType\" : \"STANDARD\", \"rg\" : \"rg\", \"cpf\" : \"cpf\", \"id\" : \"046b6c7f-0b8a-43b9-b35d-6489e6daee91\", \"state\" : \"state\", \"updatedAt\" : \"2000-01-23T04:56:07.000+00:00\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    /**
     * GET /passengers/exists : Check passenger existence by cpf
     *
     * @param cpf  (required)
     * @return Exists response (status code 200)
     */
    @Operation(
        operationId = "passengerExists",
        summary = "Check passenger existence by cpf",
        tags = { "Passengers" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Exists response", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ExistsResponseApi.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/passengers/exists",
        produces = { "application/json" }
    )
    
    default ResponseEntity<ExistsResponseApi> passengerExists(
        @NotNull @Parameter(name = "cpf", description = "", required = true, in = ParameterIn.QUERY) @Valid @RequestParam(value = "cpf", required = true) String cpf
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"exists\" : true }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    /**
     * GET /passengers : Search passengers
     *
     * @param cpf  (optional)
     * @param createdFrom  (optional)
     * @param createdTo  (optional)
     * @param page  (optional, default to 1)
     * @param size  (optional, default to 20)
     * @return Paged passengers (status code 200)
     */
    @Operation(
        operationId = "searchPassengers",
        summary = "Search passengers",
        tags = { "Passengers" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Paged passengers", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = PagedPassengerResponseApi.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/passengers",
        produces = { "application/json" }
    )
    
    default ResponseEntity<PagedPassengerResponseApi> searchPassengers(
        @Parameter(name = "cpf", description = "", in = ParameterIn.QUERY) @Valid @RequestParam(value = "cpf", required = false) String cpf,
        @Parameter(name = "createdFrom", description = "", in = ParameterIn.QUERY) @Valid @RequestParam(value = "createdFrom", required = false) @DateTimeFormat(iso = DateTimeFormat.ISO.DATE_TIME) LocalDateTime createdFrom,
        @Parameter(name = "createdTo", description = "", in = ParameterIn.QUERY) @Valid @RequestParam(value = "createdTo", required = false) @DateTimeFormat(iso = DateTimeFormat.ISO.DATE_TIME) LocalDateTime createdTo,
        @Min(1) @Parameter(name = "page", description = "", in = ParameterIn.QUERY) @Valid @RequestParam(value = "page", required = false, defaultValue = "1") Integer page,
        @Min(1) @Max(200) @Parameter(name = "size", description = "", in = ParameterIn.QUERY) @Valid @RequestParam(value = "size", required = false, defaultValue = "20") Integer size
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"totalItems\" : 5, \"size\" : 5, \"totalPages\" : 2, \"page\" : 1, \"items\" : [ { \"zipCode\" : \"zipCode\", \"address\" : \"address\", \"totalSpent\" : 6.027456183070403, \"city\" : \"city\", \"userId\" : \"046b6c7f-0b8a-43b9-b35d-6489e6daee91\", \"birthDate\" : \"2000-01-23\", \"createdAt\" : \"2000-01-23T04:56:07.000+00:00\", \"totalTrips\" : 0, \"preferredCabinType\" : \"STANDARD\", \"rg\" : \"rg\", \"cpf\" : \"cpf\", \"id\" : \"046b6c7f-0b8a-43b9-b35d-6489e6daee91\", \"state\" : \"state\", \"updatedAt\" : \"2000-01-23T04:56:07.000+00:00\" }, { \"zipCode\" : \"zipCode\", \"address\" : \"address\", \"totalSpent\" : 6.027456183070403, \"city\" : \"city\", \"userId\" : \"046b6c7f-0b8a-43b9-b35d-6489e6daee91\", \"birthDate\" : \"2000-01-23\", \"createdAt\" : \"2000-01-23T04:56:07.000+00:00\", \"totalTrips\" : 0, \"preferredCabinType\" : \"STANDARD\", \"rg\" : \"rg\", \"cpf\" : \"cpf\", \"id\" : \"046b6c7f-0b8a-43b9-b35d-6489e6daee91\", \"state\" : \"state\", \"updatedAt\" : \"2000-01-23T04:56:07.000+00:00\" } ] }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    /**
     * PUT /passengers/{id} : Update passenger
     *
     * @param id  (required)
     * @param passengerDTOApi  (required)
     * @return Passenger updated (status code 200)
     *         or Passenger not found (status code 404)
     */
    @Operation(
        operationId = "updatePassenger",
        summary = "Update passenger",
        tags = { "Passengers" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Passenger updated", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = PassengerDTOApi.class))
            }),
            @ApiResponse(responseCode = "404", description = "Passenger not found")
        }
    )
    @RequestMapping(
        method = RequestMethod.PUT,
        value = "/passengers/{id}",
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    
    default ResponseEntity<PassengerDTOApi> updatePassenger(
        @Parameter(name = "id", description = "", required = true, in = ParameterIn.PATH) @PathVariable("id") UUID id,
        @Parameter(name = "PassengerDTOApi", description = "", required = true) @Valid @RequestBody PassengerDTOApi passengerDTOApi
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"zipCode\" : \"zipCode\", \"address\" : \"address\", \"totalSpent\" : 6.027456183070403, \"city\" : \"city\", \"userId\" : \"046b6c7f-0b8a-43b9-b35d-6489e6daee91\", \"birthDate\" : \"2000-01-23\", \"createdAt\" : \"2000-01-23T04:56:07.000+00:00\", \"totalTrips\" : 0, \"preferredCabinType\" : \"STANDARD\", \"rg\" : \"rg\", \"cpf\" : \"cpf\", \"id\" : \"046b6c7f-0b8a-43b9-b35d-6489e6daee91\", \"state\" : \"state\", \"updatedAt\" : \"2000-01-23T04:56:07.000+00:00\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }

}
